### ISSUE TITLE
Star symbol `*` should allow filtering the results

### ISSUE THREAD

**Issue by max-baz** [jsantiagoh/cerebro-pass#1]
Hey @jsantiagoh, thanks for this super-nice plugin!

I have one suggestion: 
Currently when I type `*`, whatever I type afterwards does not seem to have any effect.
However, I can use `*` to filter the results when using `$ pass` directly, like so:

```
❯  pass find "git"   
Search Terms: git
├── work
│   └── github.com
│       └── work_login
└── personal
    └── github.com
        └── personal_login

❯  pass find "p*git" 
Search Terms: p*git
└── personal
    └── github.com
        └── personal_login
```

In the second example I filtered out my work account by prefixing my search with `p*`. Could we have the same in your plugin?

**Comment by jsantiagoh** [comment]
Thanks for the issue, makes sense, I'll look into it.
