### ISSUE TITLE
Proposal to take ownership of the project

### ISSUE THREAD

**Issue by max-baz** [jsantiagoh/cerebro-pass#8]
Hey @jsantiagoh,

I've seen in https://github.com/jsantiagoh/cerebro-pass/pull/5#issuecomment-296429631 that you are no longer interested in the project. Is it still so?

I'm making a few improvements in [my fork](https://github.com/maximbaz/cerebro-pass-fork), so far I cleaned the code a bit and implemented a support for pass-otp plugin https://github.com/jsantiagoh/cerebro-pass/issues/7.

I'm interested in keeping maintaining this project, that's why I'd like to propose you to transfer ownership of this project to me (you can do it in the settings of this repository). I'll take good care of it 😉 

I'll publish my fork as a new plugin if you don't respond within a month, but I hope to avoid creating a duplicate.

**Comment by jsantiagoh** [comment]
Hey @maximbaz,

Sounds like a plan, I haven't been using cerebro for a while now and because of that I'm not finding the time to look into this project, will be glad to transfer it to you if you can keep it running.

Cheers and enjoy!

**Comment by jsantiagoh** [comment]
Github is now allowing me to transfer it to you because you have a fork I think, if you send a PR I'll merge it and then you can remove the fork and I'll transfer the project to you.

**Comment by max-baz** [comment]
I deleted the fork now (I have changes locally, I'll merge them afterwards) - try to transfer again.

Could you also make sure I can keep publishing the releases on npmjs.com? I think it's just:

```
$ npm owner add maximbaz
```

**Comment by jsantiagoh** [comment]
Done.

Thanks for taking over!

**Comment by max-baz** [comment]
Thank you too 🙂
